"""
plot_B_roc_curve.py — ROC curve with AUC
Run: python plot_B_roc_curve.py
Needs: output/cache/model_predictions.csv (generated by plot_confusion.py)
"""
import matplotlib; matplotlib.use("Agg")
import pandas as pd, numpy as np, matplotlib.pyplot as plt, os, sys
from sklearn.metrics import roc_curve, auc
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from theme import apply_theme, save_plot, COLORS, CACHE_DIR
apply_theme()

preds_path = os.path.join(CACHE_DIR, "model_predictions.csv")
assert os.path.exists(preds_path), \
    "❌ Run plot_confusion.py first to generate model_predictions.csv"

df      = pd.read_csv(preds_path)
y_true  = df["y_true"].values
y_proba = df["y_proba"].values

fpr, tpr, _ = roc_curve(y_true, y_proba)
roc_auc     = auc(fpr, tpr)

fig, ax = plt.subplots(figsize=(7, 7))

# ROC curve
ax.plot(fpr, tpr, color=COLORS["red"], linewidth=2.5,
        label=f"LieGlass  (AUC = {roc_auc:.3f})")
ax.fill_between(fpr, tpr, alpha=0.08, color=COLORS["red"])

# Baselines
ax.plot([0, 1], [0, 1], color=COLORS["grid"], linestyle="--",
        linewidth=1.5, label="Random chance (AUC = 0.50)")
ax.axhline(0.54, color=COLORS["gray"], linestyle=":",
           linewidth=1.2, alpha=0.7, label="Human baseline (~0.54)")

# Optimal threshold point (Youden's J)
youden_idx = np.argmax(tpr - fpr)
ax.scatter(fpr[youden_idx], tpr[youden_idx], s=120,
           color=COLORS["white"], zorder=5,
           label=f"Optimal threshold")

ax.set_xlim([0, 1])
ax.set_ylim([0, 1.02])
ax.set_xlabel("False Positive Rate")
ax.set_ylabel("True Positive Rate")
ax.set_title("ROC Curve — Deception Detection")
ax.legend(loc="lower right")
plt.tight_layout()
save_plot(fig, "B_roc_curve.png")
