"""
plot_C_density.py — Predicted probability density by true class
Run: python plot_C_density.py
Needs: output/cache/model_predictions.csv (generated by plot_confusion.py)
"""
import matplotlib; matplotlib.use("Agg")
import pandas as pd, numpy as np, matplotlib.pyplot as plt, os, sys
from scipy.stats import gaussian_kde
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from theme import apply_theme, save_plot, COLORS, CACHE_DIR
apply_theme()

preds_path = os.path.join(CACHE_DIR, "model_predictions.csv")
assert os.path.exists(preds_path), \
    "❌ Run plot_confusion.py first to generate model_predictions.csv"

df      = pd.read_csv(preds_path)
y_true  = df["y_true"].values
y_proba = df["y_proba"].values

lie_probs   = y_proba[y_true == 0]
truth_probs = y_proba[y_true == 1]

x = np.linspace(0, 1, 300)

fig, ax = plt.subplots(figsize=(10, 5))

for probs, label, color in [
    (lie_probs,   "True Lie",   COLORS["lie"]),
    (truth_probs, "True Truth", COLORS["truth"]),
]:
    kde  = gaussian_kde(probs, bw_method=0.15)
    dens = kde(x)
    ax.plot(x, dens, color=color, linewidth=2.5, label=label)
    ax.fill_between(x, dens, alpha=0.15, color=color)

ax.axvline(0.5, color=COLORS["white"], linestyle="--",
           linewidth=1.5, alpha=0.8, label="Decision boundary (0.5)")

ax.set_xlabel("Model Confidence  —  P(Lie)")
ax.set_ylabel("Density")
ax.set_title("Prediction Confidence by True Class")
ax.legend()
ax.text(0.01, 0.97,
        "Well-separated peaks = confident, calibrated model",
        transform=ax.transAxes, va="top",
        fontsize=9, color=COLORS["gray"], fontstyle="italic")
plt.tight_layout()
save_plot(fig, "C_density.png")
